<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H290O4K" failures="1" tests="1" name="testCases.ExecuteTask.Notification.TC031_NT_ET_ETRS_DTAfterMinutes" time="40.943" errors="0" timestamp="2025-01-10T15:42:42 IST" skipped="0">
  <testcase classname="testCases.ExecuteTask.Notification.TC031_NT_ET_ETRS_DTAfterMinutes" name="testExecuteTask__DTAfterMinutes" time="40.943">
    <failure message="Home Page Not Displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Home Page Not Displayed
at org.testng.Assert.fail(Assert.java:111)
at testCases.ExecuteTask.Notification.TC031_NT_ET_ETRS_DTAfterMinutes.testExecuteTask__DTAfterMinutes(TC031_NT_ET_ETRS_DTAfterMinutes.java:140)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- testExecuteTask__DTAfterMinutes -->
</testsuite> <!-- testCases.ExecuteTask.Notification.TC031_NT_ET_ETRS_DTAfterMinutes -->
